### ISSUE TITLE
An entry with the same key already exists.

### ISSUE THREAD

**Issue by quirrel1002** [kawansoft/AceQL.Client#1] opened 2020-06-05 11:49 UTC
hello,
it seems I hit an parameter name parsing issue this thime.
when I execute the follwing statement with c# client (I used AceQL.Client.WinFormTest project):
`string sql = "INSERT INTO dbo.PACKAGE (NAMESPACEID, NAME) VALUES (@NAMESPACEID, @NAME) RETURNING ID";
AceQLCommand command = new AceQLCommand(sql2, connection);
command.Parameters.AddWithValue("@NAMESPACEID", 478);
command.Parameters.AddWithValue("@NAME", "AWS - TEST3");
AceQLDataReader dataReader = await command.ExecuteReaderAsync()`

it fails with the following error message:

`"errorType: 0 / reason: An entry with the same key already exists. / httpStatusCode: OK / exception: System.ArgumentException: An entry with the same key already exists.\r\n   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)\r\n   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)\r\n   at AceQL.Client.Api.Util.AceQLCommandUtil.GetPreparedStatementParametersDic()\r\n   at AceQL.Client.Api.Util.AceQLCommandUtil.GetPreparedStatementParameters()\r\n   at AceQL.Client.Api.AceQLCommand.<ExecuteQueryAsPreparedStatementAsync>d__20.MoveNext()"`

if I change paramter @NAME to e.g. @NAME1 the query executes as expected.
I hope you can help in resolving the issue

**Comment by ndepomereu** [comment] 2020-06-05 12:00
Hi,

Thanks.
Probably a search error in AceQL code because a param string is a substring
of another param string.

I will investigate asap.

Regards,
Nicolas


Le ven. 5 juin 2020 à 13:49, quirrel1002 <notifications@github.com> a
écrit :

**Comment by ndepomereu** [comment] 2020-06-06 22:12
The problem is fixed in version 4.2.1. See [release notes](https://github.com/kawansoft/AceQL.Client/blob/master/RELEASE-NOTES.txt).

**Closed by ndepomereu** 2020-06-06 22:12 UTC

**Comment by quirrel1002** [comment] 2020-06-08 08:59
Thanks for the quick response. I also can verify the issue is solved with v4.2.1 of AceQL.Client.
